// File generated by FlutterFire CLI — updated for project thackur-4ee4e.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── New project: thackur-4ee4e (project number 665723405514) ──

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBdi8I7qPJ19pLMZI5H0VnH3-7U4XSSY',
    appId: '1:665723405514:android:f1c84c3ee7e8be18f2a033',
    messagingSenderId: '665723405514',
    projectId: 'thackur-4ee4e',
    storageBucket: 'thackur-4ee4e.firebasestorage.app',
  );

  // Web / Windows / iOS — update if you add those platforms to the new project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBdi8I7qPJ19pLMZI5H0VnH3-7U4XSSY',
    appId: '1:665723405514:android:f1c84c3ee7e8be18f2a033',
    messagingSenderId: '665723405514',
    projectId: 'thackur-4ee4e',
    authDomain: 'thackur-4ee4e.firebaseapp.com',
    storageBucket: 'thackur-4ee4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmBdi8I7qPJ19pLMZI5H0VnH3-7U4XSSY',
    appId: '1:665723405514:android:f1c84c3ee7e8be18f2a033',
    messagingSenderId: '665723405514',
    projectId: 'thackur-4ee4e',
    storageBucket: 'thackur-4ee4e.firebasestorage.app',
    iosBundleId: 'com.example.thackur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmBdi8I7qPJ19pLMZI5H0VnH3-7U4XSSY',
    appId: '1:665723405514:android:f1c84c3ee7e8be18f2a033',
    messagingSenderId: '665723405514',
    projectId: 'thackur-4ee4e',
    storageBucket: 'thackur-4ee4e.firebasestorage.app',
    iosBundleId: 'com.example.thackur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmBdi8I7qPJ19pLMZI5H0VnH3-7U4XSSY',
    appId: '1:665723405514:android:f1c84c3ee7e8be18f2a033',
    messagingSenderId: '665723405514',
    projectId: 'thackur-4ee4e',
    authDomain: 'thackur-4ee4e.firebaseapp.com',
    storageBucket: 'thackur-4ee4e.firebasestorage.app',
  );
}